Sprint 3
Ren22/middle.messenger.praktikum.yandex pull request #3
Opened 2021-11-11 00:44 UTC by Ren22

2021-11-15 15:04 UTC, ua9msn requested changes
В целом не плохо. Но есть места, которые можно улучшить

2021-11-15 15:04 UTC, ua9msn commented on src/baseClasses/EventBus.ts
>      });
Разве событие не может возикнуть если его никто не  слушает?

2021-11-15 17:07 UTC, Ren22 commented on src/components/chatContact/chatContact.ts
> +
Привет, а ты бы мог посмотреть в нетлифай как это работает у меня? Вроде бы все нормально срабатывает, но могу ошибаться..

2021-11-15 23:35 UTC, Ren22 commented on src/global/colors.less
> +@lavender: #E4EDFD;
 хмм, но если один и тот же цвет используется для разных элементов?

2021-11-15 23:49 UTC, Ren22 commented on src/services/chatsService.ts
>  }
Понял, То есть лучше все  try/catch навесить в этом файле , а не в controllers ?

2021-11-15 23:50 UTC, Ren22 commented on src/baseClasses/EventBus.ts
>      });
не очень тут понял, что именно надо поправить @ua9msn

2021-11-16 06:24 UTC, ua9msn commented on src/services/chatsService.ts
>  }
Да. Если вы захотите обрабатывать исключения выше - всегда можно сделать `trow new Exception`  в блоке `catch`

2021-11-16 06:28 UTC, ua9msn commented on src/global/colors.less
> +@lavender: #E4EDFD;
Не экономте на спичках. Никто не мешает назначить разным константам одно значение. Но зато смена цветовой темы пройдет безболезненно. 
> И при этом не все бордеры имеют #CCC?   

Значит это разные переменные, `border_Generic` `border_Error` ну или что там у вас.

2021-11-16 06:33 UTC, ua9msn commented on src/baseClasses/EventBus.ts
>      });
Я очень часто встречаю такой не правильный паттерн. Смотрите: Есть объект который бросает событие. Почему вдруг он не может бросить событие, если его никто не слушает? У вас событие сожается слушателем в функции `on`. Но функция `emit` вызывается произвольным объектом, он не обязан знать что его кто то слушает. 
Если провести аналогию - у вас выходит что автомобиль не может сигналить если вокруг нет пешеходов. Допустим ему и не нужно сигналить, но по вашему коду, если он посигналит без пешеходов, то сломется.

2021-11-16 15:18 UTC, Ren22 commented on src/global/colors.less
> +@lavender: #E4EDFD;
в том то и дело , что один цвет используется для разных компонетов) можно посмотреть макеты тут https://www.figma.com/file/24EUnEHGEDNLdOcxg7ULwV/Chat?node-id=0%3A1

2021-11-16 17:02 UTC, ua9msn commented on src/global/colors.less
> +@lavender: #E4EDFD;
Ну и что? Выделите типы использования. Допустим 
```
 @mesageBackground: grey;
 @contactBackground: grey;
 @genericBorder: darkGrey; 
```
Если дизайн поменяется и для контаков нужно будет сделать другой цвет вы его просто добавите `@contactBorder: red`.

2021-11-17 01:03 UTC, Ren22 commented on src/baseClasses/EventBus.ts
>      });
Вообще я думал функция emit вызывается только как метод EventBus. То есть без инициализации объекта класса EventBus я не смогу вызвать emit из другого объекта. Или имеется в виду статичный вызов? Но если я правильно понял коммент выше , то надо 

```
  emit(event: string, ...args: any[]) {
    if (!this.listeners[event]) {
      throw new Event(event);
    }
    this.listeners[event].forEach(function callListener(listener) {
      listener(args);
    });
  }
```
?

2021-11-17 01:04 UTC, Ren22 commented on src/global/colors.less
> +@lavender: #E4EDFD;
постараюсь поправить в следующей итерации

2021-11-17 01:04 UTC, Ren22 commented on src/baseClasses/EventBus.ts
>      });
@ua9msn

2021-11-17 16:26 UTC, ua9msn commented on src/baseClasses/EventBus.ts
>      });
EventBus - это синглтон, он один на все приложение. Этот паттерн как раз и предназанчен для общения между модулями, для того что бы уменьшить связность. В вашем случае `emit` вообще не должен брость исключений а все возможные события дожны быть опеределены в костантном объекте

2021-11-17 17:58 UTC, Ren22 commented on src/baseClasses/EventBus.ts
>      });
понял, это я что-то намудрил с исключением, хотел просто вызвать событие как `new CustomEvent(event);` запушил новый коммит. У меня на самом деле eventBus - это не синглтон. например я ввожу локальныйl ocalEventBus в chatList.ts . Но понял, что надо отрефакторить и сделать синглтон из eventBus-a.

2021-11-18 13:30 UTC, ua9msn commented
Давайте я приму у вас работу что бы не задерживать.

2021-11-18 23:13 UTC, Ren22 commented
> Давайте я приму у вас работу что бы не задерживать.

спасибо , постараюсь отрефакторить и закрыть проблемные части на доп неделе

2021-11-18 23:19 UTC, merged